{% set version = "1.17.0" %}

package:
  name: ucx-split

source:
  url: https://github.com/openucx/ucx/releases/download/v{{ version }}/ucx-{{ version }}.tar.gz
  sha256: 34658e282f99f89ce7a991c542e9727552734ac6ad408c52f22b4c2653b04276

build:
  skip: true  # [not (linux64 or aarch64) or cuda_compiler_version == "None"]
  number: 1

outputs:
  - name: ucx
    version: {{ version }}
    build:
      run_exports:
        - {{ pin_subpackage("ucx", max_pin="x.x") }}
      ignore_run_exports_from:
        - {{ compiler("cuda") }}
        - cuda-cudart-dev          # [(cuda_compiler_version or "None").startswith("12")]
      missing_dso_whitelist:
        - "*libcuda.so*"
        - "*libcudart.so*"
        - "*libnvidia-ml.so*"
    requirements:
      build:
        - {{ stdlib("c") }}
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("cuda") }}
        - automake
        - autoconf
        - libtool
        - make
        - pkg-config
        - libgomp
      host:
        - cuda-version {{ cuda_compiler_version }}
        - cuda-cudart-dev          # [(cuda_compiler_version or "None").startswith("12")]
        - cuda-nvml-dev            # [(cuda_compiler_version or "None").startswith("12")]
        - rdma-core
      run_constrained:
        - cuda-version >=11.2,<12  # [(cuda_compiler_version or "None").startswith("11")]
        - cuda-version >=12,<13    # [(cuda_compiler_version or "None").startswith("12")]
        # The actual version constraint comes from cuda-version, so below we explicit list
        # them only to codify that these are expected (but optional) dependencies when CUDA
        # is in use.
        - cudatoolkit              # [(cuda_compiler_version or "None").startswith("11")]
        - cuda-cudart              # [(cuda_compiler_version or "None").startswith("12")]

    script: install_ucx.sh
    test:
      commands:
        - test -f "${PREFIX}/lib/libucp${SHLIB_EXT}"
        - test ! -f "${PREFIX}/lib/libucp.a"
        - test -f "${PREFIX}/lib/libucm${SHLIB_EXT}"
        - test ! -f "${PREFIX}/lib/libucm.a"
        - test -f "${PREFIX}/lib/libucs${SHLIB_EXT}"
        - test ! -f "${PREFIX}/lib/libucs.a"
        - test -f "${PREFIX}/lib/libuct${SHLIB_EXT}"
        - test ! -f "${PREFIX}/lib/libuct.a"
        - test -f "${PREFIX}/bin/.ucx-post-link.sh"
        - test -f "${PREFIX}/bin/ucx_info"
        # Fails on ppc64le
        - ucx_info -v  # [not ppc64le]
    about:
      home: https://openucx.org
      license: BSD-3-Clause
      license_family: BSD
      license_file: LICENSE
      summary: Unified Communication X.
      dev_url: https://github.com/openucx/ucx
      doc_url: https://openucx.readthedocs.io/

about:
  home: https://github.com/openucx/ucx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Unified Communication X.
  dev_url: https://github.com/openucx/ucx
  doc_url: https://openucx.readthedocs.io/

extra:
  recipe-maintainers:
    - Akshay-Venkatesh
    - jakirkham
    - quasiben
    - TomAugspurger
    - leofang
    - matthiasdiener
    - xhochy
