{% set ucx_version = "1.9.0" %}
{% set ucx_proc_version = "1.0.0" %}
{% set number = "0" %}

{% set ucx_proc_type = "cpu" if cuda_compiler_version == "None" else "gpu" %}


package:
  name: ucx-split

source:
  url: https://github.com/openucx/ucx/archive/v{{ ucx_version }}.tar.gz
  sha256: 36d0f6b8a7948361082f65be67b4c6336ebf2db62d717f253206ec7276a29086

build:
  skip: true  # [not linux]
  number: 2

outputs:
  - name: ucx-proc
    version: {{ ucx_proc_version }}
    build:
      number: 2
      string: "{{ ucx_proc_type }}"
    test:
      commands:
        - exit 0
    about:
      home: https://github.com/conda-forge/ucx-feedstock
      license: BSD-3-Clause
      license_family: BSD
      summary: A meta-package to select CPU or GPU UCX build.

  - name: ucx
    version: {{ ucx_version }}
    build:
      number: {{ number }}
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("cuda") }}         # [cuda_compiler_version != "None"]
        - {{ cdt("libnl") }}             # [cdt_name == "cos6"]
        - {{ cdt("libnl3") }}            # [cdt_name == "cos7"]
        - {{ cdt("libibcm-devel") }}     # [cdt_name == "cos6"]
        - {{ cdt("libibverbs-devel") }}  # [cdt_name == "cos6"]
        - {{ cdt("librdmacm-devel") }}   # [cdt_name == "cos6"]
        - {{ cdt("numactl-devel") }}
        - {{ cdt("rdma-core-devel") }}   # [cdt_name == "cos7"]
        - automake
        - autoconf
        - libtool
        - make
        - pkg-config
      host:
      run_constrained:
        - ucx-proc * {{ ucx_proc_type }}
    script: install_ucx.sh
    test:
      commands:
        - test -f "${PREFIX}/bin/ucx_info"
        # Requires driver for GPU test.
        - ${PREFIX}/bin/ucx_info -v         # [cuda_compiler_version == "None"]
    about:
      home: https://github.com/openucx/ucx
      license: BSD-3-Clause
      license_family: BSD
      license_file: LICENSE
      summary: Unified Communication X.

about:
  home: https://github.com/openucx/ucx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Unified Communication X.

extra:
  recipe-maintainers:
    - Akshay-Venkatesh
    - jakirkham
    - quasiben
    - TomAugspurger
